server:
  port: 8080
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: myjava123
    username: shima
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.OracleLegacyDialect
    debug: true
