server:
  port: 8080
j2os:
  class: shima

spring:
  datasource:
    password: myjava123
    username: shima
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.community.dialect.OracleLegacyDialect
    debug: true
secretJwtString : secretJwtString123456789secretJwtString123456789secretJwtString123456789secretJwtString123456789secretJwtString
