version: '3.8'

services:
  oracle-db:
    image: oracle/database:19.3.0-ee
    container_name: shima_oracle
    restart: always
    environment:
      - ORACLE_PWD= Aa!123456
      - ORACLE_SID=shima
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata

  app:
    build: .
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521:xepdb1
      SPRING_DATASOURCE_USERNAME: shima
      SPRING_DATASOURCE_PASSWORD: myjava123
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

volumes:
  oracle-data: {}
